name: Website Monitor

on:
  schedule:
    # - cron: "*/60 * * * *"  # Tiap 60 menit
    - cron: "0 1 * * *"   # 08:00 WIB
    - cron: "0 14 * * *"   # 17:00 WIB
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Install dependencies
        run: pip install requests cloudscraper

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python monitor.py